version: '3'

services:
  personal-website:
    image: ccr.ccs.tencentyun.com/zcyyds1110/personal-website:latest
    container_name: personal-website
    restart: always
    ports:
      - "80:80"
  
  todo-app:
    image: docker.io/amir20/dozzle-todo:latest
    container_name: todo-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///./todo.db