version: '3'
services:
  web:
    image: docker.io/zcyyds1110/my-app:latest
    ports:
      - "8120:80"
    restart: always
  
  todo:
    build: ./todo-app
    ports:
      - "8121:3000"
    restart: always