name: Deploy to Tencent Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t personal-website .
      
    - name: Log in to Tencent Cloud
      uses: docker/login-action@v1
      with:
        registry: ccr.ccs.tencentyun.com
        username: ${{ secrets.TENCENT_CLOUD_ACCESS_KEY }}
        password: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
    
    - name: Push image to Tencent Cloud
      run: |
        docker tag personal-website ccr.ccs.tencentyun.com/zcyyds1110/personal-website:latest
        docker push ccr.ccs.tencentyun.com/zcyyds1110/personal-website:latest
    
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TENCENT_SERVER_IP }}
        username: ${{ secrets.TENCENT_SERVER_USER }}
        key: ${{ secrets.TENCENT_SERVER_SSH_KEY }}
        script: |
          docker pull ccr.ccs.tencentyun.com/zcyyds1110/personal-website:latest
          docker-compose down
          docker-compose up -d